### ISSUE TITLE
Start a testing notebook

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#215]
It's time to start making an online notebook of tests for our changes which requires some ingenuity.

We can just make a new directory in ci, and then divide that up by release with a directory structure kind of like this:

```
testing_notebook
  v3.0.0
    index
    test1
    ...
```

The index should map description, issue # (if there is one and PR#s if not), to filename. This can be taken from the changelog.

So, it should look like:

```
test1
- Make devnode D-Bus properties consistent across restarts of stratisd:
  https://github.com/stratis-storage/stratisd/pull/2661
```

We need only do the ones that require imagination, like the one for setting the pool state to no-ipc-requests.

**Comment by mulkieran** [comment]
More-or-less up-to-date stratisd changelog PR: https://github.com/stratis-storage/stratisd/pull/2666.

**Comment by bgurney-rh** [comment]
I added the "no-ipc-requests" test, though I'm not sure what PR that maps to.  I also don't know if I want to have tests that are named "test1", so I chose a short descriptive filename.  (Perhaps that won't be scalable long-term.)
