### ISSUE TITLE
Document way to test libblkid check for when initializing a device and udev information is incorrect

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#235]
Related https://github.com/stratis-storage/stratisd/issues/1506

**Comment by mulkieran** [comment]
@jbaublitz Plz drop an explanation of the testing mechanism, i.e., the particular udev rules used into the testing notebook. Then @bgurney-rh can run the test and add any additional information he thinks is useful.

**Comment by jbaublitz** [comment]
@bgurney-rh Here is the udev rule:

```
ENV{DEVNAME}=="/dev/loop0", ENV{ID_FS_USAGE}="", ENV{ID_FS_TYPE}="", ENV{ID_PART_TABLE_TYPE}=""
```

Make the value for `DEVNAME` whatever device you're testing. Next run `cryptsetup luksFormat /dev/loop0` to make it a LUKS2 device. After that, `stratis pool create testpool /dev/loop0` should fail with:

```
Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: At least one of the devices specified was unsuitable for initialization: Device /dev/loop0 was reported to be unowned by udev but actually contains existing partitions or superblock; partitions: None, superblock: Some("crypto_LUKS"). 
```
