### ISSUE TITLE
Using wrong cargo in stratisd tests

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/ci#38]
We've been running into failures on [this PR](https://github.com/stratis-storage/stratisd/pull/1629) for the `stratisd` tests. I think I've tracked it down to the fact that Rust is being installed and source is being compiled from the root directory while the `PATH` environment variable is pointing at a user home directory. This would explain why we get errors about using unstable features that are already stable. It seems we're using an outdated `cargo` without realizing it.

**Comment by bgurney-rh** [comment]
This seems to be an artifact of long-running test systems across upgraded versions of cargo / rust.  Here's a view on one of the CI test systems:

```
$ ~/.cargo/bin/cargo -V
cargo 1.37.0 (9edd08916 2019-08-02)
$ sudo ~/.cargo/bin/cargo -V
cargo 1.31.0 (339d9f9c8 2018-11-16)
```

**Comment by bgurney-rh** [comment]
Something else I was thinking about (keeping in mind that all of the test scripts are executed via "sudo"):

In the ci repository, the greps of PATH:
```
$ grep -nIR export\ PATH ./*
./cli.sh:4:export PATH="$HOME/.cargo/bin:$PATH"
./dm_test.sh:4:export PATH="$HOME/.cargo/bin:$PATH"
./stratisd_nonrust.sh:4:export PATH="$HOME/.cargo/bin:$PATH"
./stratisd.sh:4:export PATH="$HOME/.cargo/bin:$PATH"
```
...and "cargo clean" is executed after the PATH variable is configured, as required by rust:
```
$ grep -nIR cargo\ clean ./*
./dm_test.sh:17:cargo clean
./stratisd_nonrust.sh:24:cargo clean
./stratisd.sh:46:cargo clean
```

**Comment by mulkieran** [comment]
We'll use a Jenkins-set environment variable to specify the Rust toolchain absolute path.

**Comment by mulkieran** [comment]
We can fix this more directly be removing the "sudo env" part of the make target for these tests, see: https://github.com/stratis-storage/stratisd/pull/1673.

**Comment by mulkieran** [comment]
Closed by linked PRs.
