### ISSUE TITLE
Something not quite right with the cli-with-stratisd test infrastructure

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#39]
These are tests that run the stratis-cli tests when there is a PR against stratisd. The stratisd PR is checked, and then the tests from stratis-cli master are run.

These have begun to fail. We believe that the failures are consistent w/ the stratis-cli tests being run against an old version of stratisd.

But also, we think that these tests/machines are somehow irregularly maintained, and that that's really the source of the problem.

Rather significantly, the version of the rust toolchain is 1.31, which means that the test scripts haven't been updated in quite a while, as all the other similar tests are using Rust toolchain 1.37.
This test seems to have been left behind in the big sweep that got all the other tests organized.

As it happens, this test is also the most redundant part of our CI. The same tests are also run whenever a stratis-cli PR is made. In this case, the version of stratisd that is used is master and the version of stratis-cli is obviously the PR one. 

So, we have a grid like this:

```
                                                             stratis-cli tests
PR                                   stratis-cli version      |        stratisd version
-----------------------------------------------------------------------------------------------------
stratisd                                  master HEAD         |                 PR
stratis-cli                                     PR            |              master HEAD

```

These tests would catch a bug in a stratisd PR that otherwise would not be detected until the stratisd PR would be merged and a new stratis-cli PR was made. So, it seems like we should keep these tests, but if we do make a mistake while they are out of commission our other tests
will catch the problem when the stratisd PR gets merged. Meanwhile the dbus tests in stratisd,
the stratisd-nonrust tests, do test the dbus behavior fairly well. So, we are not that likely to generate such a bug.

**Comment by bgurney-rh** [comment]
The cli-with-stratisd test hasn't been updated in a while; it still calls "rustup default 1.31.0".

The test script itself also isn't in source control.  (Should it be?  We could probably get it running in a similar fashion to the other ci scripts.)

**Comment by mulkieran** [comment]
We'll can let the new script debut in the ci repo when the test is up and running again.

**Comment by mulkieran** [comment]
There's a new revised script in the CI: https://github.com/stratis-storage/ci/pull/41. So we can re-enable the test in Jenkins, but not yet require it in the GitHub settings. If it looks good, we'll re-enable it in the GitHub settings and have it also gate the CI.

**Comment by mulkieran** [comment]
It looks healthy to me, I'll go ahead and make it mandatory again.

**Comment by mulkieran** [comment]
Ok! I think that we can close this now.
