### ISSUE TITLE
Find Alternative to using rustup in CI testing

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/ci#4]
Currently the CI testing scripts call download and install from a rust site.  We might want to remove our
dependency for this by either removing rustup or cloning the files in a different location.  

This will help provide control of what is running in test and security.

**Comment by mulkieran** [comment]
I think we should close this as obsolete. We still do have dependencies on rustup in our Jenkins tests and in Travis. But we are managing pretty well, making sure to get the correct version when we run our tests. The concepts of lowest supported and current recommended Rust toolset are holding up reasonably well. The packaged versions of Rust do not deviate much or at all from the upstream version and the release of packages generally tracks the release of a new upstream version quite closely.
