### ISSUE TITLE
cli-with-stratisd is still using an old toolchain

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/ci#46]
The Kleene operator (`?`) in macros should be stable by now but the toolchain used in cli-with-stratisd is failing saying it is unstable.

**Comment by mulkieran** [comment]
I've made the test non-mandatory, so it won't erroneously gate our builds. We should try to fix it sometime in November.

**Comment by bgurney-rh** [comment]
Interesting:
```
$ rustc  --version
rustc 1.31.0 (abe02cefd 2018-12-04)
```

I also noticed that the cli-with-stratisd CI script doesn't have a "rustup default" call.  Should there be one?

**Comment by jbaublitz** [comment]
If you call `rustup default stable` for example, that will keep the toolchain current with the stable release at that time. Similarly, doing `rustup default 1.38.0` will ensure that that is the active version when the tests are run.

**Comment by bgurney-rh** [comment]
I created PR #49 to add the "rustup default" command (1.37.0 for now; this is in sync with the other CI test scripts, so we can update them together as necessary), as well as "cargo clean".

I gave it a quick test run on a spare test VM, and it looks good (though that system didn't have an older version of rust on it

**Comment by mulkieran** [comment]
Resolved by #49.
