### ISSUE TITLE
Document necessary changes for test machines when moving the D-Bus API up one major release

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#47]
When we do this, we need to upgrade various systemd configuration files on the tests machines, or the D-Bus based tests will stop being able to communicate w/ stratisd.

**Comment by jbaublitz** [comment]
Where are we looking to document this? It's documented in the D-Bus API reference on https://stratis-storage.github.io. Do we also want to add it somewhere else?

**Comment by mulkieran** [comment]
@bgurney-rh Do you feel comfortable relying on what you know from experience and the information in the D-Bus API reference? If so, you should feel free to close this.

**Comment by mulkieran** [comment]
Ok, closing.
