### ISSUE TITLE
Update CI to copy log to github gist so that all can see (Jenkins)

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/ci#5]
We need to copy the log files to a public place so that all can see the error result, one option is a github gist.

**Comment by bgurney-rh** [comment]
Unfortunately, the CI test logs can potentially contain internal information, which would need to be redacted.  Currently, the work to redact would be far more than what it would take for one of the stratis developers to post the error itself (after trimming out the less relevant noise up to the point of failure.)

So for now, I'd like to close this, but I'll want to look at it later, if or when we get to a point where redaction becomes easier than manually relaying the errors.
