### ISSUE TITLE
Should we use standard Fedora packaging instead of rustup for Jenkins tests?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#55]

**Comment by jbaublitz** [comment]
I think this all depends on whether we'll ever want to switch profiles on machines. By this I mean switching from stable to beta, etc. If all we're concerned with is version bumps and we're confident that we'll never need to jump to another channel, Fedora packaging makes sense. If we will ever want to switch to nightly on a Jenkins machine, rustup is the only supported way to do this at the moment.

**Comment by mulkieran** [comment]
As we migrate more and more to GitHub Actions (which uses rustup and it would be most convenient for it to continue to do so) the question is a little different: should the remaining few Jenkins based tests use Fedora packaging for rust?. I think this would be an administrative burden, for sure, as we generally try to run our Jenkins tests using our lowest supported toolchain. Unless we change our minds about that, we shouldn't pursue this any further.
