### ISSUE TITLE
Track all CI input via source control

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/ci#6]
It would be good to have all input (if possible) be controlled from within the source control itself.  That way we can change and track them over time and change them together in one spot.  This will prevent cases where we change test behavior and have to change each of the test nodes to ensure they work together with the change too.

Subissues:
* #7
* #16
* #20
* #22

**Comment by mulkieran** [comment]
@bgurney-rh I think you've done most of what we were looking for, if not all. If you think this can be closed, please go ahead and close it.

**Comment by bgurney-rh** [comment]
Agreed; I think we have most of the CI test scripting in the repository, to the point where any other adjustments that need to be made are minor.
