### ISSUE TITLE
Enhance cleanup script to tidy up encrypted devices

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#71]
As we do regular testing with encrypted devices now, we sometimes leave them hanging around on Jenkins machines.

We need to characterize them, figure out how to identify them unambiguously, and add some additional functionality to the cleanup script to remove them.

**Comment by mulkieran** [comment]
Probably blocked by https://github.com/stratis-storage/stratisd/issues/1935. We expect to be adding a "stratis-" prefix, which should help identify the devices to remove.

**Comment by mulkieran** [comment]
Unblocked now. @bgurney-rh Now that we have names with prefix "stratis" for the crypt devices, does that make it easier to extend the cleanup script to remove them?

**Comment by bgurney-rh** [comment]
Yes, it does.  (Sorry about the late reply; I added in the ci PR to make the addition to the teardown script.)
