### ISSUE TITLE
Find a meaningful ordering for dependencies in dependencies_fedora.sh

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#84]
Alphabetical will do, and will help to eliminate duplicates.

But it's further reasonable to split things out more semantically and alphabetize within categories.

For example:
```
# toolchain
    ... toolchain dependencies, e.g., make, clang
# other
    ... everything else
```

would be a reasonable way to get started. This way users can see more easily at a glance what they are getting into.

Related: stratis-storage/project#177

**Comment by bgurney-rh** [comment]
I just noticed that "make" is listed twice; I can fix that alongside this.

The idea behind the original ordering was to have the most vital dependencies for the build process at the top of the list (e.g.: "git" is necessary to be able to clone the other repositories, even if the ci repository was simply copied to an instance; "make" is core to the build process in general, etc.).

**Comment by mulkieran** [comment]
> I just noticed that "make" is listed twice; I can fix that alongside this.
> 
> The idea behind the original ordering was to have the most vital dependencies for the build process at the top of the list (e.g.: "git" is necessary to be able to clone the other repositories, even if the ci repository was simply copied to an instance; "make" is core to the build process in general, etc.).

That ordering makes sense to me.

That's why I thought ```toolchain```, then ```others``` categorization would kind of work. ```make``` and ```git``` certainly belong in ```toolchain```. There is a sense, though, in which ```make``` and ```git``` are somewhat more fundamental, than, say ```clang``` which also belongs in ```toolchain```. So maybe a third category would be helpful. Anything will do, so long as it's an organization and users can make sense of it.

**Comment by bgurney-rh** [comment]
I have this example, based on the following priority list:

- The program to manage repositories (git)
- The program to orchestrate building (make)
- The base toolchain (llvm, gcc)
- The core library dependencies (cryptsetup, D-Bus, systemd, xfsprogs)
- The giant mess of python3 dependencies

Right now, it looks like this:
```
dnf -y install git \
        make \
        clang \
        gcc \
        glibc-devel.i686 \
        glibc-devel.x86_64 \
        llvm \
        llvm-devel \
        cryptsetup-devel \
        dbus-devel \
        dbus-devel.i686 \
        dbus-devel.x86_64 \
        dbus-glib-devel \
        dbus-python \
        dbus-python-devel \
        device-mapper-persistent-data \
        keyutils \
        openssl-devel \
        systemd-devel \
        systemd-devel.i686 \
        systemd-devel.x86_64 \
        xfsprogs \
        python3-coverage \
        python3-dateutil \
        python3-justbytes \
        python3-psutil \
        python3-pyparsing \
        python3-pytest \
        python3-pyudev \
        python3-setuptools \
        python3-wcwidth
```

**Comment by mulkieran** [comment]
I think that's good! Is there a way to get comments in there to give titles to the groups?

**Comment by bgurney-rh** [comment]
Unfortunately, bash will consider the chain of line continuations broken if they are interrupted with a comment.  So perhaps it would be best to leave a comment above the entire line, to hint at the groups of alphabetized sections.

**Comment by mulkieran** [comment]
I figured. A comment at the top will have to do then. Also, you might as well throw in the new dependency the PYthon semantic_version library into this script while you're here.
