### ISSUE TITLE
Add "modify" mode to blackbox test script

### ISSUE THREAD

**Issue by bgurney-rh** [stratis-storage/ci#86]
Currently, the `blackbox/stratis-blacbkox-run.sh` script removes the previously created repository directories for stratisd and stratis-cli, re-clones them from stratis-storage, builds, and runs the blackbox tests.

Via modifications in the patch below, it's possible to have the script leave the previously created directories, in order to allow a run on its current contents (which could be the repository directory from a patch series, potentially to both stratisd and stratis-cli.

```
--- a/blackbox/stratis-blackbox-run.sh
+++ b/blackbox/stratis-blackbox-run.sh
@@ -62,18 +62,18 @@ fi
 mkdir output_rpms
 mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS}/
 
-# Remove the previously created repository directories
-rm -rf ${STRATISD_N}-${STRATISD_V}
-rm -rf ${STRATIS_CLI_N}-${STRATIS_CLI_V}
+# LEAVE the previously created repository directories
+# rm -rf ${STRATISD_N}-${STRATISD_V}
+# rm -rf ${STRATIS_CLI_N}-${STRATIS_CLI_V}
 
 
 # Build the stratisd package (along with the rust cargo vendor tarball)
 echo "Building stratisd test package..."
-git clone $STRATISD_REPO
+# git clone $STRATISD_REPO
 echo "Most recent commits for ${STRATISD_N}:"
-( cd $STRATISD_N; git status; git log --format="%h %ci :: %s" | head -20 )
-mv -v ${STRATISD_N} ${STRATISD_N}-${STRATISD_V}
-mkdir ${STRATISD_N}-${STRATISD_V}/vendor
+( cd ${STRATISD_N}-${STRATISD_V}; git status; git log --format="%h %ci :: %s" | head -20 )
+# mv -v ${STRATISD_N} ${STRATISD_N}-${STRATISD_V}
+# mkdir ${STRATISD_N}-${STRATISD_V}/vendor
 tar czvf ~/rpmbuild/SOURCES/${STRATISD_N}-${STRATISD_V}.tar.gz ${STRATISD_N}-${STRATISD_V}
 cd ${STRATISD_N}-${STRATISD_V}/
 cargo vendor && tar cJf ../${STRATISD_N}-${STRATISD_V}-vendor.tar.xz vendor/
@@ -84,10 +84,10 @@ rpmbuild -bb stratisd.spec
 
 # Build the stratis-cli package
 echo "Building stratis-cli test package..."
-git clone $STRATIS_CLI_REPO
+# git clone $STRATIS_CLI_REPO
 echo "Most recent commits for ${STRATIS_CLI_N}:"
-( cd $STRATIS_CLI_N; git status; git log --format="%h %ci :: %s" | head -20 )
-mv -v ${STRATIS_CLI_N} ${STRATIS_CLI_N}-${STRATIS_CLI_V}
+( cd ${STRATIS_CLI_N}-${STRATIS_CLI_V}; git status; git log --format="%h %ci :: %s" | head -20 )
+# mv -v ${STRATIS_CLI_N} ${STRATIS_CLI_N}-${STRATIS_CLI_V}
 tar czvf ~/rpmbuild/SOURCES/${STRATIS_CLI_N}-${STRATIS_CLI_V}.tar.gz ${STRATIS_CLI_N}-${STRATIS_CLI_V}
 echo "Executing rpmbuild for stratis-cli..."
 rpmbuild -bb stratis-cli.spec
-- 
2.18.1
```

I'd like to have a way to use this "modify" mode via a parameter to `blackbox/stratis-blacbkox-run.sh`, which could allow for prior scripts to pre-stage modifications to be tested.

**Comment by mulkieran** [comment]
What about splitting out the part of the script that builds the RPMs into its own script and call that from this script? That new script would clean up its directories. Then the flag to ```stratis-blackbox-run.sh``` would control whether the new script was called or not. That would also be nice for just generally creating rpms and making them available to others, as we sometimes need to do.

**Comment by bgurney-rh** [comment]
I think there might be a couple of splits:

- A script to erase the existing source directories and re-clone from upstream
- A script to perform the package build stages (vendor, rpmbuild, etc.)

I remember that there are times where I only want to pre-populate the upstream repos, so that script alone could be useful as a "pre-stage" to running a test patch.

**Comment by mulkieran** [comment]
I _think_ we should consider ourselves to be done w/ this.
