### ISSUE TITLE
Remove keyutils as a dependency for the project

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#92]
I believe we no longer use it anywhere in testing. I think we will want to leave, or add, libkeyutils-dev everywhere.

**Comment by mulkieran** [comment]
I think we should just change the keyutils dependency into libkeyutils-dev in the dependencies_fedors.sh script, and then we will be done.

**Comment by bgurney-rh** [comment]
Do you mean "keyutils-libs-devel"?

**Comment by bgurney-rh** [comment]
Looking on a VM that I created today, which ran ran the previous CI tests, I see "keyutils-libs" installed.

**Comment by mulkieran** [comment]
> Do you mean "keyutils-libs-devel"?

Likely I do. But better check w/ @jbaublitz.

**Comment by jbaublitz** [comment]
We probably need `keyctl` for cleanup operations so we still want `keyutils-libs` but `keyutils-libs-devel` can go.

**Comment by bgurney-rh** [comment]
Ok, so right now, the script is installing `keyctl` explicitly, and then `keyutils-libs` is being installed as a dependency.

I only mentioned `keyutils-libs-devel` because that's what appeared via search; by default, it's not installed in the current dependency chain.

**Comment by mulkieran** [comment]
We decided to remove it all. Everything is currently managed through stratisd, which uses syscalls.
