### ISSUE TITLE
Run stratis-cli tests from previous version against stratisd on a nightly or weekly basis

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#97]
These would be similar to our blackbox tests, as they would not run as part of our CI.

The motivation is the following:

We are currently running dbus_interface tests in stratisd, but are planning on dropping them for the reasons stated in the PR: https://github.com/stratis-storage/stratisd/pull/2085.

One benefit that would have been nice to get out of these tests would have been the ability to get testing against older version of the D-Bus API, to ensure no regressions. We can do a valuable approximation of that, one that will catch the most important errors, by running old versions of the CLI tests, which rely on old versions of the D-Bus API against the current version of stratisd.
We would run the tests from stratis-cli v2.0.0 and v2.0.1 only, since 2.0.0 was a breaking change.

One complicating factor is that the older versions of the CLI have different dependencies from the newer versions of the CLI, as we've removed some dependencies, like pytest, but added others, like, semantic_version. We will have to decide how to deal with that. Maybe fedora_dependencies.sh should take a parameter, indicating the version?

This might be worth while doing w/ the blackbox tests as well.

**Comment by bgurney-rh** [comment]
Could this potentially be a variant of the cli-with-stratisd test job, using an older release of stratis-cli?

**Comment by mulkieran** [comment]
Yes, definitely.

**Comment by bgurney-rh** [comment]
Are there two "make dbus-tests" targets (one in stratis-cli, one in stratisd)?  I didn't seem to see the tests in the "dbus_interface" suite get executed until I modified the variant of cli_with_stratisd.sh to this:
```
cd $STRATIS_DEPS_DIR/stratis-cli
# Set the PYTHONPATH to use the dependencies
export PYTHONPATH=src:$STRATIS_DEPS_DIR/dbus-client-gen/src:$STRATIS_DEPS_DIR/dbus-python-client-gen/src:$STRATIS_DEPS_DIR/into-dbus-python/src:$STRATIS_DEPS_DIR/dbus-signature-pyparsing/src
# Set the stratisd binary base location to $WORKSPACE
export STRATISD=$WORKSPACE/target/debug/stratisd
make dbus-tests

# Now switch to the stratisd tests directory
cd $WORKSPACE/tests/client-dbus
make dbus-tests
```

**Comment by mulkieran** [comment]
> Are there two "make dbus-tests" targets (one in stratis-cli, one in stratisd)? I didn't seem to see the tests in the "dbus_interface" suite get executed until I modified the variant of cli_with_stratisd.sh to this:
> 
> ```
> cd $STRATIS_DEPS_DIR/stratis-cli
> # Set the PYTHONPATH to use the dependencies
> export PYTHONPATH=src:$STRATIS_DEPS_DIR/dbus-client-gen/src:$STRATIS_DEPS_DIR/dbus-python-client-gen/src:$STRATIS_DEPS_DIR/into-dbus-python/src:$STRATIS_DEPS_DIR/dbus-signature-pyparsing/src
> # Set the stratisd binary base location to $WORKSPACE
> export STRATISD=$WORKSPACE/target/debug/stratisd
> make dbus-tests
> 
> # Now switch to the stratisd tests directory
> cd $WORKSPACE/tests/client-dbus
> make dbus-tests
> ```

Yes, there are. But you only really want to execute the ones that belong to the CLI, you should ignore all the tests in stratisd.

**Comment by mulkieran** [comment]
This is all set up.
